-- =============================================================================
-- Truncate all tables — clears all data, preserves schema and policies
-- CASCADE handles foreign key dependencies automatically
-- =============================================================================

truncate table
  public.admin_invitations,
  public.admin_users,
  public.order_fulfillment_items,
  public.order_return_items,
  public.order_refunds,
  public.order_fulfillments,
  public.order_returns,
  public.order_line_items,
  public.orders,
  public.payment_sessions,
  public.payment_collections,
  public.cart_shipping_methods,
  public.cart_line_items,
  public.carts,
  public.promotion_usages,
  public.promotion_rules,
  public.promotions,
  public.price_list_prices,
  public.price_list_customer_groups,
  public.price_lists,
  public.prices,
  public.price_sets,
  public.inventory_reservations,
  public.inventory_levels,
  public.inventory_items,
  public.product_variant_option_values,
  public.product_option_values,
  public.product_options,
  public.product_tag_products,
  public.product_collection_products,
  public.product_category_products,
  public.product_images,
  public.product_variants,
  public.products,
  public.product_tags,
  public.product_collections,
  public.product_categories,
  public.sales_channel_products,
  public.sales_channels,
  public.tax_rate_product_categories,
  public.tax_rates,
  public.tax_regions,
  public.shipping_option_requirements,
  public.shipping_options,
  public.shipping_profiles,
  public.fulfillment_providers,
  public.stock_locations,
  public.customer_addresses,
  public.customers,
  public.customer_groups,
  public.countries,
  public.regions,
  public.currencies
restart identity cascade;